<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVijd4xz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVijd4xz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVijd4xz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVijd4xz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVijd4xz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vijd4xz',
    'container.build_id' => '268fd21a',
    'container.build_time' => 1534055953,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVijd4xz');
